apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/davgordo/GitOps-OSSM/elasticsearch-operator/overlays/stable?ref=add-rollouts
  - https://github.com/davgordo/GitOps-OSSM/openshift-distributed-tracing-operator/overlays/stable?ref=add-rollouts
  - https://github.com/davgordo/GitOps-OSSM/kiali-operator/overlays/stable?ref=add-rollouts
  - https://github.com/davgordo/GitOps-OSSM/openshift-servicemesh/operator/overlays/stable?ref=add-rollouts
